### ISSUE TITLE
Support for credentials file?

### ISSUE THREAD

**Issue by iiro** [neillturner/knife-cfn#14]
Hi,

would it be possible to get support for AWS credentials file? knife-ec2 got it a while ago...

**Comment by neillturner** [comment]
ok i can copy the code from knife-ec2 if you will test it.

**Comment by iiro** [comment]
@neillturner sure, no problem.

**Comment by iiro** [comment]
@neillturner One more thing... Would it be able to get support for AWS session token as well? It seems to exist on knife-ec2 as well...

knife-cfn has been an excellent tool for us - many thanks for it! :)

**Comment by neillturner** [comment]
@iiro If you could 
 download https://github.com/neillturner/knife-cfn/blob/credentials-file/knife-cfn-0.1.11.gem
and then 
 gem install knife-cfn-0.1.11.gem
and test i would be grateful.

**Comment by neillturner** [comment]
@iiro did you get a chance to test?

**Comment by iiro** [comment]
@neillturner sorry... Get this error now:

/Users/username/.chefdk/gem/ruby/2.1.0/gems/knife-cfn-0.1.11/lib/chef/knife/cfn_create.rb:20:in `<class:Knife>': superclass must be a Class (Module given) (TypeError)
	from /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/knife-cfn-0.1.11/lib/chef/knife/cfn_create.rb:19:in `<class:Chef>'
	from /Users/iiro/.chefdk/gem/ruby/2.1.0/gems/knife-cfn-0.1.11/lib/chef/knife/cfn_create.rb:18:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:104:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:118:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:137:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:198:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:54:in `load'
	from /usr/local/bin/knife:54:in `<main>'

with every knife cfn command.

Ideas...?

**Comment by neillturner** [comment]
ok. i'll have to test myself.

**Comment by neillturner** [comment]
@iiro  i fixed and tested so should work now so 
 If you could again 
download https://github.com/neillturner/knife-cfn/blob/credentials-file/knife-cfn-0.1.11.gem
and then installed updated   knife-cfn-0.1.11.gem
and test i would be grateful. 
if i don't hear from you in 2 weeks i will just go ahead and release. -)

**Comment by iiro** [comment]
@neillturner excellent, works like a charm :) :)

**Comment by neillturner** [comment]
great i'll release it

**Comment by neillturner** [comment]
in release 0.1.11
